title: Chuan Lu (@orcuslc)
description: Be Epic, and do things that MATTER.
baseurl: ""
show_downloads: true
google_analytics:
theme: jekyll-theme-architect

author:
  name: Orcuslc
  gravatar: 436e2542ad8e21f41e94ac565d7d8c64
  description: RESEARCHER,DEVELOPER,LIFE-LEARNER,ADVENTURER,CHALLENGER,PUNKER
  contact:
    homepage: http://chuanlu.xyz
    github: https://github.com/orcuslc
    linkedin: https://www.linkedin.com/in/chuanlu
    email: http://www.google.com/recaptcha/mailhide/d?k=01c45SpzE8Ks9X2wb4RCT5Sg==&c=oMx8fFsZfQPv88sxko2cqjD-hUj8T6i2-OL4VYgn0Q4=

nav:
  Home:
    - '/'
  Blog:
    - '/blog/'
    - { Categories: '/blog/categories' }
    - { Tags: '/blog/tags' }
  About:
    - '/about/'
  GitHub:
    - 'https://github.com/orcuslc/orcuslc.github.io'

tag_page: '/blog/tags'
category_page: '/blog/categories'

plugins:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty
sass:
  style: compressed
  sass_dir: _sass