<<<<<<< HEAD
title: Chuan Lu (@orcuslc)
description: Be Epic, and do things that MATTER.
show_downloads: true
google_analytics:
theme: jekyll-theme-architect

author:
  gravatar: 436e2542ad8e21f41e94ac565d7d8c64
  description: Mathematician,Researcher,Developer,Historian,Photographer,Musician