# Site settings
title: Chuan Lu
subtitle: (Orcuslc)
email: orcuslc@hotmail.com
description: Technical Blog of Chuan
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://orcuslc.github.io" # the base hostname & protocol for your site
author: Chuan
street_address: 440 Guoding Road
city: Fudan University
state: Shanghai
zip_code: 200433
country: P.R.C
phone: +86-152-2192-5008

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/orcuslc
# gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/0/116131504514907782570
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/chuanlu
pinterest_url:
slack_url:
twitter_url: https://twitter.com/orcuslc

# Build settings
markdown: kramdown

sass:
  style: compressed
