# Where things are
collections:
  my_categories:
    output: true
    permalink: /blog/category/:name/
  my_tags:
    output: true
    permalink: /blog/tag/:name/

# Handling Reading
exclude: [Gemfile, README.md]

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Conversion
markdown:    kramdown
highlighter: rouge
excerpt_separator: "\n\n\n"

# Outputting
permalink: /post/:title/
paginate: 5
paginate_path: '/blog/page/:num/'
timezone: Asia/Beijing

defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
  -
    scope:
      path: ""
      type: my_categories
    values:
      layout: blog_by_category
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: blog_by_tag
  -
    scope:
      path: "project"
    values:
      layout: project

sass:
  style: compressed

# Custom
# domain: minddust.com
url: https://orcuslc.github.io
title: Chuan
description: Computational Sciences
copyright: 2017 Chuan Lu
name: Chuan
author: Chuan
twitter:
  username: orcuslc
github:
  username: orcuslc
linkedin_url: https://www.linkedin.com/in/chuanlu
mail: orcuslc@hotmail.com